---
abstract: 'WSDL to Perl classes when building your dist'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Cwd: 0
  Dist::Zilla::Tester: 4.101550
  File::Find: 0
  File::Temp: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-WSDL
requires:
  Dist::Zilla::Role::BeforeBuild: 0
  Dist::Zilla::Role::Tempdir: 0
  English: 0
  File::Copy: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  Regexp::DefaultFlags: 0
  SOAP::WSDL::Expat::WSDLParser: 0
  SOAP::WSDL::Factory::Generator: 0
  autodie: 0
  perl: 5.008_008
  utf8: 0
resources:
  bugtracker: http://github.com/mjg/Dist-Zilla-Plugin-WSDL/issues
  homepage: http://github.com/mjg/Dist-Zilla-Plugin-WSDL/tree
  repository: git://github.com/mjg/Dist-Zilla-Plugin-WSDL.git
version: 0.102600
