---
abstract: 'WSDL to Perl classes when building your dist'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-WSDL
requires:
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::Tempdir: 0
  English: 0
  IPC::System::Simple: 0
  Modern::Perl: 0
  Moose: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Regexp::DefaultFlags: 0
  SOAP::WSDL: 2.00.05
  perl: 5.010
  utf8: 0
version: 0.102370
